# Generated by Django 5.0.2 on 2024-04-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduHub', '0003_alter_grade_grade_alter_grade_module1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='course',
        ),
        migrations.AddField(
            model_name='group',
            name='courses',
            field=models.ManyToManyField(to='EduHub.course'),
        ),
    ]
